MarketPlaceGit/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlaceGit.Models
{
    public class Categoria
    {
        [Key]
        public int IdCategoria { get; set; }

        public int? IdPadre { get; set; }

        public string NombreCategoria { get; set; }

        public bool EstadoLogico { get; set; }
    }
}

MarketPlaceGit/Models/ErrorViewModel.cs
namespace MarketPlaceGit.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarketPlaceGit/Models/Producto.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlaceGit.Models
{
    public class Producto
    {
        [Key]
        public int IdProducto { get; set; }

        public int IdCategoria { get; set; }

        public string Nombre { get; set; }

        public string Descripcion { get; set; }

        public string UrlImagen { get; set; }

        public decimal Precio { get; set; }

        public int CantidadVisitas { get; set; }

        public bool EstadoLogico { get; set; }
    }
}

MarketPlaceGit/Models/ProductoCat.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlaceGit.Models
{
    public class ProductoCat
    {
        [Key]
        public int IdProducto { get; set; }

      

        public string Nombre { get; set; }

        public string Descripcion { get; set; }

        public string UrlImagen { get; set; }

        public decimal Precio { get; set; }

        public int CantidadVisitas { get; set; }

        public bool EstadoLogico { get; set; }

        public string NombreCategoria { get; set; }

    }
}

MarketPlaceGit/Models/ValorVariacion.cs
using System.ComponentModel.DataAnnotations;
namespace MarketPlaceGit.Models
{
    public class ValorVariacion
    {
        [Key]
        public int IdValor { get; set; }

        public string Valor { get; set; }

        public int IdVariacion { get; set; }

        public bool EstadoLogico { get; set; }
    }
}

MarketPlaceGit/Models/Variaciones.cs
using System.ComponentModel.DataAnnotations;

namespace MarketPlaceGit.Models
{
    public class Variaciones
    {
        [Key]
        public int IdVariacion { get; set; }

        public string Nombre { get; set; }

        public int IdProducto { get; set; }

        public bool EstadoLogico { get; set; }
    }
}

MarketPlaceGit/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using MarketPlaceGit.Models;
using System.Numerics;
using MarketPlaceGit.Data;
using Microsoft.EntityFrameworkCore;

namespace MarketPlaceGit.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _db;
       // private readonly IHttpContextAccessor _context;

        public CategoriaController(ApplicationDbContext db)
        {
            _db = db;
       //     _context = httpcontextAccesor;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AgregarCategoria()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AgregarCategoria(Categoria obj)
        {

            obj.EstadoLogico = true;


            var parametros = new[]
        {
            new SqlParameter("@Nombre", obj.NombreCategoria),
            
        };

            try
            {
                _db.Database.ExecuteSqlRaw("EXEC addCategoria @Nombre" 
                , parametros);
                return RedirectToAction("ExitoRegistro");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }



            return RedirectToAction("Error", "Home");
        }

        public JsonResult ObtenerCategorias()
        {
            string comSql = "Exec listarCategorias";
            IEnumerable<Categoria> listaProv = _db.Categorias.FromSqlRaw(comSql);

            return Json(listaProv.ToList());
        }
        public IActionResult ExitoRegistro()
        {
            return View();
        }

    }
}

MarketPlaceGit/Controllers/HomeController.cs
using MarketPlaceGit.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MarketPlaceGit.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketPlaceGit/Controllers/ProductoController.cs
using MarketPlaceGit.Data;
using MarketPlaceGit.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MarketPlaceGit.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _db;
        // private readonly IHttpContextAccessor _context;

        public ProductoController(ApplicationDbContext db)
        {
            _db = db;
            //     _context = httpcontextAccesor;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AgregarProducto()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AgregarProducto(Producto obj)
        {

            obj.EstadoLogico = true;


            var parametros = new[]
        {
            new SqlParameter("@IdCategoria",  obj.IdCategoria),
            new SqlParameter("@Nombre",  obj.Nombre),
            new SqlParameter("@Descripcion",  obj.Descripcion),
            new SqlParameter("@UrlImagen",  obj.UrlImagen),
            new SqlParameter("@Precio",  obj.Precio),
            

        };

            try
            {
                _db.Database.ExecuteSqlRaw("EXEC productosAddProducto @IdCategoria, " +
                "@Nombre, @Descripcion, @UrlImagen, @Precio"
                , parametros);
                return RedirectToAction("ExitoRegistro");
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }



            return RedirectToAction("Error", "Home");
        }

        public JsonResult ObtenerProductos()
        {
            string comSql = "select * from ProductosCat ";
            IEnumerable<ProductoCat> listaProv = _db.ProductosCat.FromSqlRaw(comSql);

            return Json(listaProv.ToList());
        }

        public IActionResult ExitoRegistro()
        {
            return View();
        }
    }
}

MarketPlaceGit/Views/Categoria/AgregarCategoria.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Categoria
<form method="post">

    <h3 class="text-danger">Nueva Categoria</h3>
    <h5 class="text-danger">Favor Registrar los datos de la Categoria</h5>
    <div class="form-floating mb-3">
        <input type="text"
               class="form-control"
               id="inputNombreCategoria"
               asp-for="NombreCategoria"
               required
               placeholder="Nombre Categoria" />
        <label for="inputNombreCategoria">Nombre Plan</label>
    </div>
    

            <p class="text-danger fw-bold text-end p-3" id="pCostoFijo">Costo Fijo Total</p>
        </div>
    </div>
    <div class="container mt-3">
        <button type="submit" name="buttonRegistrar" class=" mb-3 col-12 btn btn-primary btn-block">Guardar Categoria</button>
        <a asp-controller="Usuario" asp-action="DashAdmin" class=" mb-1 col-12 btn btn-info" style="display: inline-block;">Cancelar</a>

    </div>

</form>

MarketPlaceGit/Views/Categoria/ExitoRegistro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h5 class="text-center m-5">Exito</h5>
<a class="btn btn-primary col-12" asp-controller="Home" asp-action="Index">Regresar al inicio</a>

MarketPlaceGit/Views/Home/Index.cshtml
@{
    Layout = null;
}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        display: flex;
        flex-direction: column;
    }

    header {
        background-color: #4CAF50;
        color: white;
        text-align: center;
        padding: 1em;
        position: relative;
    }

    .search-bar {
        margin-top: 10px;
    }

        .search-bar input {
            padding: 10px;
            width: 300px;
            border: none;
            border-radius: 5px;
            margin-right: 10px;
        }

        .search-bar button {
            padding: 10px;
            background-color: #333;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

    #cart {
        position: absolute;
        right: 20px;
        top: 20px;
        font-size: 1.1em;
    }

    aside {
        padding: 20px;
        width: 250px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        margin: 20px;
    }

        aside h3 {
            margin-top: 0;
        }

    .filter {
        margin-bottom: 20px;
    }

    #products {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        margin: 2em;
        flex-grow: 1;
    }

    .product {
        background-color: white;
        border: 1px solid #ddd;
        border-radius: 8px;
        margin: 10px;
        padding: 20px;
        width: 200px;
        text-align: center;
    }

        .product img {
            width: 100%;
            height: auto;
            border-radius: 5px;
        }

        .product h3 {
            font-size: 1.2em;
            color: #333;
        }

        .product p {
            color: #555;
        }

        .product button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
        }

            .product button:hover {
                background-color: #45a049;
            }

    /* Estilos del modal */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
</style>
<header>
    <h1>Bienvenido al Marketplace de Componentes para PC</h1>
    <div class="search-bar">
        <input type="text" id="searchInput" placeholder="Buscar componentes...">
        <button id="searchButton">Buscar</button>
    </div>
    <div id="cart">
        <span>Carrito: <span id="cartCount">0</span> items</span>
    </div>
</header>

<aside>
    <h3>Filtros</h3>
    <div class="filter">
        <h4>Categoría</h4>
        <select id="categoryFilter">
            <option value="all">Todas</option>
            <option value="cpu">CPU</option>
            <option value="gpu">GPU</option>
            <option value="motherboard">Placa Base</option>
            <option value="ram">RAM</option>
            <option value="storage">Almacenamiento</option>
            <option value="Monitores">Monitores</option>
        </select>
    </div>

    <div class="filter">
        <h4>Precio</h4>
        <input type="range" id="priceFilter" min="0" max="1000" value="1000">
        <span id="priceValue">$1000</span>
    </div>
</aside>

<section id="products">
    <!-- Aquí se cargarán los productos -->
</section>

<!-- Modal -->
<div id="productModal" style="display: none;">
    <div class="modal-content">
        <span class="close" style="cursor:pointer;">&times;</span>
        <img id="modalProductImage" src="" alt="Imagen del producto" style="width: 100px;">
        <h3 id="modalProductName"></h3>
        <p id="modalProductDescription"></p>
        <p id="modalProductPrice"></p>
        <button id="addToCartButton">Agregar al Carrito</button>
    </div>
</div>

@* <a class="btn btn-primary col-12" asp-controller="Home" asp-action="AgregarProducto">Agregar Nuevo Producto</a> *@

<script>
    let allProducts = [];
    document.addEventListener('DOMContentLoaded', function () {
        //let allProducts = [];
        let cartCount = 0;
        var data;

        //llenado de select Categoria
        const selectCategorias = document.getElementById("categoryFilter");

        addEventListener('load', cargaProductos, false);

        var conexion1;
        function cargaProductos() {
            conexion1 = new XMLHttpRequest();
            conexion1.onreadystatechange = procesarEventos1;
            conexion1.open("GET", "@Url.Action("ObtenerProductos", "Producto")", true);
            conexion1.send();
        }

        function procesarEventos1() {

            if (conexion1.readyState == 4) {


                data = JSON.parse(conexion1.responseText);
                allProducts = data;
                displayProducts(data)
                data.forEach(
                    function (objeto) {

                        console.log(objeto.nombre + ' ' + objeto.precio)

                    }
                )
            }
        }



        // Cargar productos desde el archivo JSON
        fetch('./webservice/productos.json') // Corregido
            .then(response => response.json())
            .then(data => {
                allProducts = data;
                displayProducts(allProducts); // Mostrar todos los productos al inicio
            })
            .catch(error => console.error('Error al cargar los productos:', error));

        // Mostrar productos en la página
        function displayProducts(products) {
            const productsContainer = document.getElementById('products');
            productsContainer.innerHTML = ''; // Limpiar productos previos

            products.forEach(product => {
                const productDiv = document.createElement('div');
                productDiv.classList.add('product');

                productDiv.innerHTML = `
                    <img src="${product.urlImagen}" alt="${product.nombre}">
                    <h3>${product.nombre}</h3>
                    <p>${product.descripcion}</p>
                    <p>Precio: $${product.precio}</p>
                    <button class="view-details">Ver Detalles</button>
                `;

                productsContainer.appendChild(productDiv);

                // Evento para ver detalles del producto
                const viewDetailsButton = productDiv.querySelector('.view-details');
                viewDetailsButton.addEventListener('click', function () {
                    showModal(product);
                });
            });
        }

        // Mostrar modal con detalles del producto
        function showModal(product) {
            document.getElementById('modalProductName').textContent = product.name;
            document.getElementById('modalProductImage').src = product.image;
            document.getElementById('modalProductDescription').textContent = product.description;
            document.getElementById('modalProductPrice').textContent = `Precio: $${product.price}`;

            const modal = document.getElementById('productModal');
            modal.style.display = "block";

            // Agregar al carrito
            document.getElementById('addToCartButton').onclick = function () {
                cartCount++;
                document.getElementById('cartCount').textContent = cartCount;
                alert(`${product.name} ha sido agregado al carrito.`);
                modal.style.display = "none"; // Cerrar modal después de agregar
            };
        }

        // Cerrar el modal
        const closeModal = document.getElementsByClassName("close")[0];
        closeModal.onclick = function () {
            document.getElementById('productModal').style.display = "none";
        };

        // Filtrar por búsqueda
        const searchInput = document.getElementById('searchInput');
        const searchButton = document.getElementById('searchButton');

        searchButton.addEventListener('click', function () {
            const query = searchInput.value.toLowerCase();
            const filteredProducts = allProducts.filter(product => {
                // console.log(query);
                // console.log(product.nombre.toLowerCase());
                return product.nombre.toLowerCase().includes(query);

            }


            );
            displayProducts(filteredProducts);
            // console.log(filteredProducts);
        });

        // Filtrar por categoría
        const categoryFilter = document.getElementById('categoryFilter');
        categoryFilter.addEventListener('change', function () {
            const selectedCategory = categoryFilter.value;
            const filteredProducts = allProducts.filter(product =>
            //     {
            //     console.log(product.nombreCategoria.toLowerCase());
            //     console.log(selectedCategory.toLowerCase());
            //     selectedCategory === 'todos' || product.nombreCategoria.toLowerCase() === selectedCategory.toLowerCase()
            // }
                selectedCategory === 'all' || product.nombreCategoria.toLowerCase() === selectedCategory.toLowerCase()
            );
            displayProducts(filteredProducts);
            console.log(filteredProducts);
        });

        // Filtrar por precio
        const priceFilter = document.getElementById('priceFilter');
        const priceValue = document.getElementById('priceValue');

        priceFilter.addEventListener('input', function () {
            const maxPrice = priceFilter.value;
            priceValue.textContent = `$${maxPrice}`;

            const filteredProducts = allProducts.filter(product =>
                product.precio <= maxPrice
            );
            displayProducts(filteredProducts);
        });
    });


</script>

MarketPlaceGit/Views/Producto/AgregarProducto.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Producto
<form method="post">

    <h3 class="text-danger">Nuevo Producto</h3>
    <h5 class="text-danger">Favor Registrar los Datos del Producto</h5>

<div class="form-floating mb-3">
    <input type="text"
           class="form-control"
           id="inputIdCategoria"
           asp-for="IdCategoria"
           required
           placeholder="IdCategoria" />
    <label for="inputNombreProducto">Id Categoria</label>
</div>
<div class="form-floating mb-3">
    <input type="text"
           class="form-control"
           id="inputNombreProducto"
           asp-for="Nombre"
           required
           placeholder="Nombre Producto" />
    <label for="inputNombreProducto">Nombre Producto</label>
</div>
<div class="form-group">
    <label for="inputDescripcion">UrlImagen</label>
<textarea asp-for="UrlImagen"
          required
          class="form-control"
          name="UrlImagen"
          id="UrlImagen"
          rows="5"
          placeholder="UrlImagen"></textarea>
</div>
<div class="form-group">
    <label for="inputDescripcion">Descripcion</label>
<textarea asp-for="Descripcion"
          required
          class="form-control"
          name="Descripcion"
          id="Descripcion"
          rows="5"
          placeholder="Descripcion"></textarea>
</div>


<div class="form-floating mb-3">
    <input type="range"
           min="10"
           max="1000"
           step="10"
           class="form-control mt-3 form-range"
           id="inputPrecio"
           asp-for="Precio"
           required
           placeholder="Precio"
           required| />

    <label for="inputPrecio">
        Precio:
        <span class="text-danger" id="displayPrecio">550</span>
    </label>
</div>







@* <div class="container mt-3">
<button type="submit" name="buttonRegistrar" class=" mb-3 col-12 btn btn-primary btn-block">Guardar Producto</button>
<a asp-controller="Usuario" asp-action="DashAdmin" class=" mb-1 col-12 btn btn-info" style="display: inline-block;">Cancelar</a>

    </div> *@

</form>

<script>
    const rangeInput = document.getElementById("inputPrecio");
    const valueDisplay = document.getElementById("displayPrecio");

    rangeInput.addEventListener("input", function () {
      valueDisplay.textContent = rangeInput.value;
    });
</script>

MarketPlaceGit/Views/Producto/ExitoRegistro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h5 class="text-center m-5">Exito</h5>
<a class="btn btn-primary col-12" asp-controller="Home" asp-action="Index">Regresar al inicio</a>

MarketPlaceGit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarketPlaceGit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MarketPlaceGit.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarketPlaceGit</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="AgregarCategoria">NuevaCategoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="AgregarProducto">NuevoProducto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MarketPlaceGit - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>